### ISSUE TITLE
How is interface using as variable type?

### ISSUE THREAD

**Issue by zklim** [Encode-Club-Solidity-Foundations/Lesson-03#3]
I've been seeing some code using inferface as variable type. Below is the code snippets:

The interface:
```Solidity
pragma solidity >=0.6.9 <0.9.0;

interface IBridge {
```

And the contract:
```Solidity
pragma solidity ^0.8.4;

import "./IBridge.sol";

contract Inbox is DelegateCallAware, PausableUpgradeable, IInbox {
    IBridge public bridge; /// IBridge is interface name and it is being used as variable type, what this means?

 function initialize(IBridge _bridge, ISequencerInbox _sequencerInbox) {
} /// some function using the interface variable type as parameter.
```

How to inteprete `bridge` variable in this case? And what's it's implication?

**Comment by MatheusDaros** [comment]
Hello @zklim 
We did see a small part of this on the lesson 2.
This is a very useful technique to apply interfaces to some addresses inside the smart contract. This doesn't change the external type of that variable, that keeps being address for whatever it is worth externally. But internally that is extremely handy so you can make external calls to those addresses by just calling the method name and passing the parameters.
